"""
    Build wordlists into JavaScript code so that we can bundle them with our code.
"""

import json


def wordListToJSON(filename):
    with open(filename) as fl:
        wlist = fl.read().split("\n")

    return "JSON.parse(`{0}`)".format(json.dumps(wlist))


with open("src/wordlist.ts", "w") as fl:
    fl.write("""
// auto-generated by build_wordlist.py

const VAR_TERMS: string[] = {0};
const CONST_TERMS: string[] = {1};
""".format(
        wordListToJSON("wordlists/vars.txt"),
        wordListToJSON("wordlists/const.txt")
    ))
